export const ADD_PRODUCT_TO_SHOPPING_CART = "ADD_PRODUCT_TO_SHOPPING_CART"
export const DECREASE_SHOPPING_CART_ITEM_QUANITY = "DECREASE_SHOPPING_CART_ITEM_QUANITY"
export const REMOVE_SC_ITEM = "REMOVE_SC_ITEM"